# Generated by Django 2.0.1 on 2018-01-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180128_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='city',
        ),
        migrations.RemoveField(
            model_name='question',
            name='state',
        ),
        migrations.RemoveField(
            model_name='question',
            name='zip',
        ),
        migrations.AddField(
            model_name='question',
            name='citystatezip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
