# Generated by Django 2.0.1 on 2018-02-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproduct',
            name='max_rental_days',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
