# Generated by Django 2.0.1 on 2018-02-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180222_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producttype',
            field=models.TextField(choices=[('BulkProduct', 'Bulk Product'), ('IndividualProduct', 'Individual Product'), ('RentalProduct', 'Rental Product')], default='IndividualProduct'),
        ),
    ]
