# Generated by Django 2.0.1 on 2018-02-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_producttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='producttype',
        ),
    ]
